version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - localmetrics
    depends_on:
      - dockerstats
  dockerstats:
    image: wywywywy/docker_stats_exporter:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9487:9487"
    networks:
      - localmetrics
  grafana:
      image: grafana/grafana
      ports:
        - "3001:3000"
      networks:
        - localmetrics
  
networks:
  localmetrics:
    driver: bridge
